# Dijkstra.srv

# request definition
# this section defines the input parameters required to complete the service.

# threat field and edges
float64[] threat
EdgeArray edges

# initial and target vertices
int32 vertex_init
int32 vertex_trgt

---

# response definition
# this section defines the output parameters that the service will return.

# path and threat metric
AlgorithmOutput result