# AlgoDijkstra.srv

# request definition
# this section defines the input parameters required to complete the service.

# threat field vertices and edges
VertexArray vertices
EdgeArray edges

# initial and target vertex indicies
int32 vertex_init
int32 vertex_trgt

---

# response definition
# this section defines the output parameters that the service will return.

# vertex indices
int64[] indices