# Dijkstra.srv

# request definition
# this section defines the input parameters required to complete the service.

# threat field and edges
float64[] threat
int32[][] edges

# initial and target vertices
int32 vertex_init
int32 vertex_trgt

---

# response definition
# this section defines the output parameters that the service will return.

# optimal path
int32[] path

# cummulative metric of optimal path
float64 metric