# UGVFollowLine.action

# goal definition
# this section defines the input parameters required to complete the action.

# initial vertex
float64 init_x
float64 init_y

# target vertex
float64 trgt_x
float64 trgt_y

---

# result definition
# this section defines the output parameters after executing the goal.

# success of the action
bool success

---

# feedback definition
# this section provides feedback during the execution of the goal.

# current local error
mess2_msgs/UGVState error_local